kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  image: kindest/node:v1.30.0
- role: worker01
  image: kindest/node:v1.30.0
- role: worker02
  image: kindest/node:v1.30.0
